import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { getReportByShareToken } from "@/lib/db/queries"

export const metadata: Metadata = { title: "Security Report — Oculs.io" }

const SEV_HEX: Record<string, string> = {
  critical: "#f87171", high: "#fb923c", medium: "#fbbf24", low: "#60a5fa", info: "#a1a1aa",
}
const SEV_ORDER = ["critical", "high", "medium", "low", "info"]

interface Props {
  params: Promise<{ token: string }>
}

export default async function PublicReportPage({ params }: Props) {
  const { token } = await params
  const report = await getReportByShareToken(token)
  if (!report) notFound()

  // Dedup by tool + title
  const map = new Map<string, { title: string; severity: string; tool: string; count: number }>()
  for (const v of report.vulns) {
    const key = `${v.tool}::${v.title}`
    const ex = map.get(key)
    if (ex) ex.count++
    else map.set(key, { title: v.title, severity: v.severity, tool: v.tool, count: 1 })
  }
  const findings = Array.from(map.values()).sort(
    (a, b) => SEV_ORDER.indexOf(a.severity) - SEV_ORDER.indexOf(b.severity),
  )
  const counts = SEV_ORDER.reduce((acc, s) => {
    acc[s] = findings.filter((f) => f.severity === s).reduce((n, f) => n + f.count, 0)
    return acc
  }, {} as Record<string, number>)

  return (
    <div className="min-h-screen bg-[#000000] text-white">
      <div className="max-w-[760px] mx-auto px-6 py-12">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <span className="text-[13px] font-mono text-[#888888]">oculs.io</span>
          <span className="text-[11px] font-mono text-[#444444]">Read-only shared report</span>
        </div>

        <p className="text-[11px] font-mono uppercase tracking-[0.12em] text-[#555555] mb-2">Security report</p>
        <h1 className="text-[24px] font-semibold" style={{ letterSpacing: "-0.72px" }}>{report.repoFullName}</h1>
        <p className="text-[13px] text-[#666666] mt-1">
          {(report.completedAt ?? report.createdAt).toLocaleString()}
        </p>

        {/* Severity summary */}
        <div className="grid grid-cols-5 gap-2 mt-8 mb-8">
          {SEV_ORDER.map((s) => (
            <div key={s} className="border border-white/10 rounded-[10px] bg-white/[0.02] px-3 py-3 text-center">
              <p className="text-[10px] font-mono uppercase tracking-[0.06em] text-[#444444] mb-1">{s}</p>
              <p className="text-[22px] font-semibold tabular-nums" style={{ color: counts[s] > 0 ? SEV_HEX[s] : "#444444" }}>
                {counts[s]}
              </p>
            </div>
          ))}
        </div>

        {/* Findings */}
        <div className="border border-white/10 rounded-[12px] overflow-hidden">
          <div className="px-5 py-3 border-b border-white/[0.07] grid grid-cols-[1fr_90px_90px] gap-4
                          text-[10px] font-mono uppercase tracking-[0.06em] text-[#444444]">
            <span>Finding</span><span>Severity</span><span>Tool</span>
          </div>
          <ul className="divide-y divide-white/[0.04]">
            {findings.length === 0 && (
              <li className="px-5 py-8 text-center text-[13px] text-[#666666]">No active findings 🎉</li>
            )}
            {findings.map((f, i) => (
              <li key={i} className="px-5 py-3.5 grid grid-cols-[1fr_90px_90px] gap-4 items-center">
                <span className="text-[13px] text-white truncate" style={{ letterSpacing: "-0.26px" }}>
                  {f.title}{f.count > 1 && <span className="text-[#555555] ml-2 font-mono text-[11px]">{f.count}×</span>}
                </span>
                <span className="inline-flex items-center h-5 px-2 rounded-[4px] border w-fit text-[10px] font-mono uppercase"
                  style={{ color: SEV_HEX[f.severity], borderColor: `${SEV_HEX[f.severity]}33`, background: `${SEV_HEX[f.severity]}14` }}>
                  {f.severity}
                </span>
                <span className="text-[11px] font-mono text-[#555555] truncate">{f.tool}</span>
              </li>
            ))}
          </ul>
        </div>

        <p className="text-[11px] font-mono text-[#444444] text-center mt-8">
          Generated by <a href="https://oculs.io" className="text-[#888888] hover:text-white">Oculs.io</a> — automated security scanning
        </p>
      </div>
    </div>
  )
}