import { GitBranch, Sparkles, CodePatch } from "@/components/ui/icons";
import type { ComponentType, SVGProps } from "react";

type IconComponent = ComponentType<SVGProps<SVGSVGElement> & { size?: number }>;

interface Feature {
  eyebrow: string;
  title: string;
  body: string;
  Icon: IconComponent;
}

const FEATURES: Feature[] = [
  {
    eyebrow: "SCAN",
    title: "Scan on every push.",
    body: "Connect your GitHub repository and Oculs runs SAST and DAST tools — Semgrep, OWASP ZAP, and Gitleaks — on every push and pull request. Zero manual configuration.",
    Icon: GitBranch,
  },
  {
    eyebrow: "TRIAGE",
    title: "AI triage in seconds.",
    body: "Google Gemini maps each finding to severity, CWE ID, and OWASP Top 10 category. Get structured, actionable results instead of raw scanner output.",
    Icon: Sparkles,
  },
  {
    eyebrow: "FIX",
    title: "Patches, ready to apply.",
    body: "Every finding comes with a unified diff patch generated by AI. Review, apply, and open a PR — directly from the Oculs dashboard.",
    Icon: CodePatch,
  },
];

export function Features() {
  return (
    <section id="features" className="bg-[#000000] relative z-10">
      <div className="mx-auto max-w-[1200px] px-4 sm:px-6">
        
        {/* Yukarıdan inen Bento kılavuz çizgileri */}
        <div className="relative w-full border-x border-b border-white/10 px-6 py-[96px] flex flex-col items-center">
          
          {/* Köşe Reticle İkonları (+) - Sadece alt köşelere */}
          <div className="absolute -bottom-[6px] -left-[4.5px] text-white/20 text-[10px] font-mono leading-none">+</div>
          <div className="absolute -bottom-[6px] -right-[4.5px] text-white/20 text-[10px] font-mono leading-none">+</div>

          {/* Section header */}
          <div className="max-w-[600px] w-full mx-auto text-center mb-16">
            <p
              className="text-[11px] font-mono uppercase tracking-[0.08em] text-[#a1a1aa] mb-4"
            >
              HOW IT WORKS
            </p>
            <h2
              className="text-[32px] font-semibold leading-[40px] text-white font-sans"
              style={{ letterSpacing: "-1.28px" }}
            >
              Push. Scan. Ship secure.
            </h2>
            <p className="mt-4 text-[16px] leading-6 text-[#a1a1aa]">
              The entire security pipeline lives inside your existing GitHub
              Actions workflow. No agents. No infrastructure.
            </p>
          </div>

          {/* 3-up card grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 w-full">
            {FEATURES.map((feature) => (
              <FeatureCard key={feature.eyebrow} {...feature} />
            ))}
          </div>

        </div>
      </div>
    </section>
  );
}

function FeatureCard({ eyebrow, title, body, Icon }: Feature) {
  return (
    <div
      className="flex flex-col gap-4 bg-white/5 border border-white/10 rounded-[8px] p-6 
                 hover:bg-white/10 transition-colors duration-200"
    >
      {/* Icon */}
      <div
        className="flex items-center justify-center w-9 h-9 rounded-[8px]
                   bg-[#000000] border border-white/10 text-white"
      >
        <Icon size={16} />
      </div>

      {/* Text */}
      <div className="flex flex-col gap-2">
        <p
          className="text-[10px] font-mono uppercase tracking-[0.08em] text-[#a1a1aa]"
        >
          {eyebrow}
        </p>
        <h3
          className="text-[20px] font-semibold leading-7 text-white font-sans"
          style={{ letterSpacing: "-0.6px" }}
        >
          {title}
        </h3>
        <p className="text-[14px] leading-5 text-[#a1a1aa]" style={{ letterSpacing: "-0.28px" }}>
          {body}
        </p>
      </div>
    </div>
  );
}
